title: emosher # site title
author: Eric Mosher # your name
description: Geek, coder/developer, musician, gamer. # description or subtitle
email: emoshmosh@gmail.com # used for gravatar

# if you copy an avatar file to ./source folder,
# just uncomment the variable below,
# and replace "avatar.png" to your image name.
# better to use 48x48 pixels.
#avatar: avatar.png

# menu buttons in header
menu:
  archives: /archives
  about: /about

# comments system
# disqus always goes first once configured
disqus_shortname:
duoshuo_shortname:

# social links
weibo: # id but not nickname, example: levicorpus / 1997375853
github: emosher # username, example: saintwinkle
gplus: # google+ id, don't forget symbol "+", example: +周一
twitter: emoshmosh # username, example: saintwinkle

# google analytics, example: UA-12345678-1
google_analytics: UA-49958928-1
